name: Release
on:
    workflow_dispatch:
    push:
        branches:
            - master, next

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "20.x"
            - run: npx semantic-release --ci=false --dry-run=false
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
